name: Update Tópicos Kafka Dev

on:
  workflow_dispatch:

jobs:
  update-topicos-kafka:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CONFIG_PATH: config.json
    steps:
      - name: Checkout repositório principal
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get Content from Wiki
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
        run: |
          echo "::group::🔍 Fetching content from Wiki.js..."
          QUERY=$(cat << EOF
          {         
            pages {
              single (id:27) {
                content
              }
            }
          }
          EOF
          )

          echo $QUERY

          echo "📤Fetching API"

          JSON_PAYLOAD=$(jq -n --arg q "$QUERY" '{query: $q}')


          RESPONSE=$(curl -s -X POST "https://wiki.franquinho.info/graphql" \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD")
          
          echo "✅ CURL Fetch Done"
          
          CONTENT=$(echo "$RESPONSE" | jq -c '.data.pages.single.content')
          echo "✅ Content fetched: $CONTENT"
          echo "CONTENT=$CONTENT" >> "$GITHUB_ENV"
          echo "::endgroup::"
      
      - name: Update Content
        env:
          CONTENT: ${{ env.CONTENT }}
        run: |
          CONFIG_FILE="${{ env.CONFIG_PATH }}"
          echo "Lendo config de: $CONFIG_FILE"
          
          topicName=$(jq -r '.metadata.topicName' "$CONFIG_FILE")
          topicDescription=$(jq -r '.metadata.topicDescription' "$CONFIG_FILE")

          link="https://dev.azure.com/CTTPortugal/Technology/_git/pt.technology.kafka.documentation?path=/$topicName"

          echo "Nome do Tópico: $topicName"
          echo "Descrição do Tópico: $topicDescription"
          
          update="| $topicName | $topicDescription | [Link]($link) | Ativo |"
          echo $update

          new_content="$CONTENT"$'\n'"$update" >> "$GITHUB_ENV"
          echo $new_content
      
      - name: Update WIKI Page
        env:
          new_content: ${{ env.new_content }}
        run: |
          echo $new_content
