name: Update Tópicos Kafka Dev

on:
  workflow_dispatch:

jobs:
  update-topicos-kafka:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get Content from Wiki
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
        run: |
          echo "::group::🔍 Fetching content from Wiki.js..."
          QUERY=$(cat << EOF
          {         
            pages {
              single (id:27) {
                content
              }
            }
          }
          EOF
          )

          echo $QUERY

          echo "📤Fetching API"

          JSON_PAYLOAD=$(jq -n --arg q "$QUERY" '{query: $q}')


          RESPONSE=$(curl -s -X POST "https://wiki.franquinho.info/graphql" \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD")
          
          echo "✅ CURL Fetch Done"
          
          CONTENT=$(echo "$RESPONSE" | jq -c '.data.pages.single.content')
          echo "✅ Content fetched: $CONTENT"
          echo "CONTENT=$CONTENT" >> "$GITHUB_ENV"
          echo "::endgroup::"
