name: Kafka3

on:
  workflow_dispatch:

jobs:
  update-topicos-kafka:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CONFIG_PATH: config.json

    steps:
      - name: Checkout repositório principal
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Content from Wiki
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
        run: |
          echo "🔍 Fetching content from Wiki.js..."
          QUERY=$(cat << EOF
          {         
            pages {
              single (id:27) {
                content
              }
            }
          }
          EOF
          )

          JSON_PAYLOAD=$(jq -n --arg q "$QUERY" '{query: $q}')

          RESPONSE=$(curl -s -X POST "https://wiki.franquinho.info/graphql" \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD")

          echo "$RESPONSE" | jq -r '.data.pages.single.content' > wiki_content.md
          echo "✅ Content saved to wiki_content.md"

      - name: Update Content
        run: |
          CONFIG_FILE="${{ env.CONFIG_PATH }}"
          topicName=$(jq -r '.metadata.topicName' "$CONFIG_FILE")
          topicDescription=$(jq -r '.metadata.topicDescription' "$CONFIG_FILE")
          link="https://dev.azure.com/CTTPortugal/Technology/_git/pt.technology.kafka.documentation?path=/$topicName"
          update="| $topicName | $topicDescription | [Link]($link) | Ativo |"

          echo "🔧 New row: $update"

          table_header="| Nome do Tópico | Descrição | Detalhes/Link Documentação | Estado |"
          table_separator="|--|--|--|--|"

          # Remove BOM da primeira linha e salva em arquivo temporário
          sed '1s/^\xEF\xBB\xBF//' wiki_content.md > wiki_content_clean.md

          # Verifica se a tabela existe
          if ! grep -Fq "$table_header" wiki_content_clean.md; then
            echo "⚠️ Tabela não encontrada. Adicionando tabela no final do arquivo."
            echo -e "\n$table_header\n$table_separator\n$update" >> wiki_content_clean.md
          else
            start_line=$(grep -nF "$table_header" wiki_content_clean.md | cut -d: -f1)
            sep_line=$((start_line + 1))
            total_lines=$(wc -l < wiki_content_clean.md)
            end_line=$sep_line

            # Encontrar o final da tabela (linhas que começam com pipe '|')
            while [ $end_line -lt $total_lines ]; do
              next_line=$((end_line + 1))
              line_content=$(sed -n "${next_line}p" wiki_content_clean.md)
              if [[ "$line_content" =~ ^\| ]]; then
                end_line=$next_line
              else
                break
              fi
            done

            # Separar arquivo em cabeçalho, tabela e resto
            head_content=$(sed -n "1,$((start_line - 1))p" wiki_content_clean.md)
            table_content=$(sed -n "$start_line,$end_line p" wiki_content_clean.md)
            tail_content=$(sed -n "$((end_line + 1)),$total_lines p" wiki_content_clean.md)

            # Extrair só as linhas da tabela sem header e separador
            table_rows=$(echo "$table_content" | grep -vF "$table_header" | grep -vF "$table_separator")

            # Verifica se tópico já existe na tabela
            if echo "$table_rows" | grep -Fq "| $topicName |"; then
              echo "⚠️ Tópico '$topicName' já existe na tabela. Nenhuma alteração feita."
            else
              echo "✅ Tópico não encontrado. Adicionando à tabela e ordenando."
              table_rows=$(echo -e "$table_rows\n$update")
              # Ordena pela segunda coluna (Nome do Tópico), ignorando espaços
              table_rows=$(echo "$table_rows" | sort -t'|' -k2,2)
            fi

            # Recria o arquivo completo com a tabela atualizada
            {
              echo "$head_content"
              echo "$table_header"
              echo "$table_separator"
              echo "$table_rows"
              echo "$tail_content"
            } > wiki_content_clean.md
          fi

          # Substitui arquivo original
          mv wiki_content_clean.md wiki_content.md

          # Prepara para upload
          cp wiki_content.md content_to_upload.md
          
          echo "⚠️⚠️⚠️ DEbug Contnet to update"
          head -30 content_to_upload.md | cat -n


      - name: Fetch current tags from Wiki.js
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
        run: |
          QUERY=$(cat << EOF
          {         
            pages {
              single (id:27) {
                tags { tag }
              }
            }
          }
          EOF
          )

          JSON_PAYLOAD=$(jq -n --arg q "$QUERY" '{query: $q}')

          RESPONSE=$(curl -s -X POST "https://wiki.franquinho.info/graphql" \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD")

          TAGS=$(echo "$RESPONSE" | jq -c '[.data.pages.single.tags[].tag]')
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"

      - name: Prepare GraphQL Payload
        env:
          TAGS: ${{ env.TAGS }}
        run: |
          echo "🛠 Preparing GraphQL payload..."

          GRAPHQL_QUERY=$(cat << 'EOF'
          mutation UpdatePage($id: Int!, $content: String!, $tags: [String!]) {
            pages {
              update(
                id: $id,
                content: $content,
                editor: "markdown",
                isPrivate: false,
                isPublished: true,
                locale: "en",
                tags: $tags
              ) {
                responseResult {
                  succeeded
                  slug
                  message
                }
                page {
                  id
                  title
                  path
                  updatedAt
                }
              }
            }
          }
          EOF
          )

          RAW_CONTENT=$(cat content_to_upload.md)

          VARIABLES=$(jq -n \
            --arg id "28" \
            --arg content "$RAW_CONTENT" \
            --argjson tags "$TAGS" \
            '{id: ($id | tonumber), content: $content, tags: $tags}')

          echo "$GRAPHQL_QUERY" > query.graphql
          echo "$VARIABLES" > variables.json

      - name: Upload Content to Wiki.js
        env:
          WIKI_API_TOKEN: ${{ secrets.WIKI_API_TOKEN }}
        run: |
          echo "🚀 Uploading updated content to Wiki.js..."

          JSON_PAYLOAD=$(jq -n \
            --arg query "$(cat query.graphql)" \
            --argjson variables "$(cat variables.json)" \
            '{query: $query, variables: $variables}')

          curl -X POST "https://wiki.franquinho.info/graphql" \
            -H "Authorization: Bearer $WIKI_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"

          echo "✅ Upload complete."
